### ISSUE TITLE
Support basic auth configuration

### ISSUE THREAD

**Issue by MattFaus** [socsieng/sublime-download-source#1]
I'd like to download source from a server which requires a basic auth username/password. When I give the URL to Download Source it fails because it does not know those details (traceback below). I would like to be able to specify these details somewhere such that the download proceeds. My server also uses a self-signed SSL certificate, which I suspect will cause other problems once the basic auth issue is resolved.

```
Traceback (most recent call last):
  File "DownloadSourceCommand in /Users/matt/Library/Application Support/Sublime Text 3/Installed Packages/Download Source.sublime-package", line 18, in on_done
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

I'm happy to work on this myself and send a pull request, per https://packagecontrol.io/docs/submitting_a_package but I wanted to reach out to you first to see if you were still active on github and could accept a pull request if I were to send it.

**Comment by socsieng** [comment]
Sorry about the late reply.

Yes, pull requests are welcome.
